In [53]:
# imports

import pandas as pd
import requests
import foursquare
import os

# Foursquare

Send a request to Foursquare with a small radius (1000m) for all the bike stations in your city of choice.

In [104]:
# Specify the path to your Notepad file
file_path_id = 'C:/Users/sarah/FSQ_id.txt'
file_path_secret = 'C:/Users/sarah/FSQ_secret.txt'
file_path_api_key = 'C:/Users/sarah/FSQ_api_key.txt'

# Read the contents of the file
with open(file_path_id, 'r') as file:
    foursquare_id = file.read()
    
with open(file_path_secret, 'r') as file:
    foursquare_secret = file.read()
        
with open(file_path_api_key, 'r') as file:
    foursquare_api_key = file.read()
    

url = "https://api.foursquare.com/v3/places/search"
params = {
    'll': '25.790654,-80.1300455', 
    'radius': 1000,
    'client_id': foursquare_id,
    'client_secret': foursquare_secret
 }
headers = {
    "Accept": "application/json",
    "Authorization": foursquare_api_key
}
response = requests.request("GET", url, params=params, headers=headers)
#response.text
print(response.status_code)
#response.json()['results']

200

In [106]:

url = "https://api.foursquare.com/v3/places/search?ll=25.790654%2C-80.1300455&radius=1000&fields=categories%2Crating%2Cgeocodes%2Ccategories%2Clocation%2Cname%2Cfsq_id%2Cstats%2Cprice&limit=50"

headers = {
    "Accept": "application/json",
    "Authorization": foursquare_api_key
}
response2 = requests.request("GET", url, headers=headers)
FSQ_Miami_Beach_POI2 = pd.DataFrame(response2.json()['results'])
#response2.text
print(response.status_code)
#response.json()['results']

200

Parse through the response to get the POI (such as restaurants, bars, etc) details you want (ratings, name, location, etc)

In [79]:
cat = pd.json_normalize(FSQ_Miami_Beach_POI2['categories'])
latlon = pd.json_normalize(FSQ_Miami_Beach_POI2['geocodes'])
address = pd.json_normalize(FSQ_Miami_Beach_POI2['location'])
result_df = pd.concat([FSQ_Miami_Beach_POI2, cat, latlon, address], axis=1)
result_df.head(2)

,fsq_id,categories,geocodes,location,name,price,rating,stats,0,1,...,address,census_block,country,cross_street,dma,formatted_address,locality,postcode,region,address_extended
0,4c4737e8c047be9a85d42f79,"[{'id': 13064, 'name': 'Pizzeria', 'icon': {'p...","{'drop_off': {'latitude': 25.790251, 'longitud...","{'address': '1627 Collins Ave', 'census_block'...",Pizza Bar Collins Ave,2.0,8.3,"{'total_photos': 275, 'total_ratings': 252, 't...","{'id': 13064, 'name': 'Pizzeria', 'icon.prefix...",None,...,1627 Collins Ave,120860042051001,US,Lincoln Road,Miami-Fort Lauderdale,"1627 Collins Ave (Lincoln Road), Miami Beach, ...",Miami Beach,33139,FL,NaN
1,563f681ccd100e6ce018b431,"[{'id': 13002, 'name': 'Bakery', 'icon': {'pre...","{'main': {'latitude': 25.791388, 'longitude': ...","{'address': '1666 Collins Ave', 'census_block'...",Rosetta Bakery,2.0,9.0,"{'total_photos': 305, 'total_ratings': 607, 't...","{'id': 13002, 'name': 'Bakery', 'icon.prefix':...","{'id': 13040, 'name': 'Dessert Shop', 'icon.pr...",...,1666 Collins Ave,120860042061007,US,16th St,Miami-Fort Lauderdale,"1666 Collins Ave (16th St), Miami Beach, FL 33139",Miami Beach,33139,FL,NaN

Put your parsed results into a DataFrame

In [130]:
cat = pd.json_normalize(FSQ_Miami_Beach_POI2['categories'])
latlon = pd.json_normalize(FSQ_Miami_Beach_POI2['geocodes'])
address = pd.json_normalize(FSQ_Miami_Beach_POI2['location'])
FSQ_Miami_Beach_POI2 = pd.concat([FSQ_Miami_Beach_POI2, cat, latlon, address], axis=1)
#FSQ_Miami_Beach_POI2.rename(columns={'main.latitude': 'latitude', 'main.longitude': 'longitude'}, inplace=True)

FSQ_Miami_Beach_POI2 = result_df[['fsq_id','name','price','rating','main.latitude','main.longitude','country','region','locality']]
FSQ_Miami_Beach_POI2.rename(columns={'main.latitude': 'latitude', 'main.longitude': 'longitude'}, inplace=True)
#FSQ_Miami_Beach_POI2

C:\Users\sarah\AppData\Local\Temp\ipykernel_20844\611045515.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  FSQ_Miami_Beach_POI2.rename(columns={'main.latitude': 'latitude', 'main.longitude': 'longitude'}, inplace=True)

In [67]:
result_df.columns

Index([            'fsq_id',         'categories',           'geocodes',
                 'location',               'name',              'price',
                   'rating',              'stats',                    0,
                          1,                    2,  'drop_off.latitude',
       'drop_off.longitude',      'main.latitude',     'main.longitude',
            'roof.latitude',     'roof.longitude',            'address',
             'census_block',            'country',       'cross_street',
                      'dma',  'formatted_address',           'locality',
                 'postcode',             'region',   'address_extended'],
      dtype='object')

In [ ]:
# Load the DataFrame from the Miami Bikes pickle file
samples_3_Miami_Bikes = pd.read_pickle('samples_3_Miami_Bikes.pk')

# Yelp

Send a request to Yelp with a small radius (1000m) for all the bike stations in your city of choice.

In [132]:
# Specify the path to your Notepad file
yelp_key = 'C:/Users/sarah/yelp_key.txt'

# Read the contents of the file
with open(yelp_key, 'r') as file:
    yelp_key = file.read()

In [133]:
import requests

#STATION 1

url = "https://api.yelp.com/v3/businesses/search"
key = yelp_key
parameters = {'latitude':25.729275,
              'longitude':-80.2415815,
              'radius' : 1000,
              'limit' : 50}
headers = {
    'Authorization': f'Bearer {key}'
}
response = requests.get(url, headers=headers, params=parameters)
response.status_code
YELP_station1 =response.json()['businesses']
YELP_station1 = pd.json_normalize(YELP_station1)
YELP_station1.head()
categories_df = pd.json_normalize(YELP_station1['categories'])
#categories_df.head()

In [141]:
#STATION 2

url = "https://api.yelp.com/v3/businesses/search"
key = yelp_key
parameters = {'latitude':25.732522,
              'longitude':-80.233244,
              'radius' : 1000,
              'limit' :50}
headers = {
    'Authorization': f'Bearer {key}'
}
response = requests.get(url, headers=headers, params=parameters)
YELP_station2 = response.json()['businesses']
#YELP_station1 = response.json()['results']
YELP_station2 = pd.json_normalize(YELP_station2)
categories_df2 = pd.json_normalize(YELP_station2['categories'])

In [142]:
#STATION 3

url = "https://api.yelp.com/v3/businesses/search"
key = yelp_key
parameters = {'latitude':25.728437,
              'longitude':-80.234443,
              'radius' : 1000,
              'limit' :50}
headers = {
    'Authorization': f'Bearer {key}'
}
response = requests.get(url, headers=headers, params=parameters)
YELP_station3 = response.json()['businesses']
#YELP_station1 = response.json()['results']
YELP_station3 = pd.json_normalize(YELP_station3)
categories_df3 = pd.json_normalize(YELP_station3['categories'])

Parse through the response to get the POI (such as restaurants, bars, etc) details you want (ratings, name, location, etc)

In [143]:
#STATION 1

# Create an empty list to store the extracted values
extracted_values = []

# Iterate over each row in the dataframe
for index, row in categories_df.iterrows():
    # Create a temporary list to store the values for the current row
    row_values = []
    
    # Iterate over each cell in the row
    for cell in row:
        if isinstance(cell, dict):
            # Extract the value associated with the 'alias' key
            value = cell.get('alias')
        else:
            value = None
        
        # Append the extracted value to the temporary list
        row_values.append(value)
    
    # Append the temporary list to the list of extracted values
    extracted_values.append(row_values)

# Create a new dataframe from the extracted values
categories_df = pd.DataFrame(extracted_values)

# Print the extracted values
#print(categories_df)

In [144]:
#STATION 2
# Create an empty list to store the extracted values
extracted_values = []

# Iterate over each row in the dataframe
for index, row in categories_df2.iterrows():
    # Create a temporary list to store the values for the current row
    row_values = []
    
    # Iterate over each cell in the row
    for cell in row:
        if isinstance(cell, dict):
            # Extract the value associated with the 'alias' key
            value = cell.get('alias')
        else:
            value = None
        
        # Append the extracted value to the temporary list
        row_values.append(value)
    
    # Append the temporary list to the list of extracted values
    extracted_values.append(row_values)

# Create a new dataframe from the extracted values
categories_df2 = pd.DataFrame(extracted_values)

# Print the extracted values
#print(categories_df)

In [145]:
#STATION 3
# Create an empty list to store the extracted values
extracted_values = []

# Iterate over each row in the dataframe
for index, row in categories_df3.iterrows():
    # Create a temporary list to store the values for the current row
    row_values = []
    
    # Iterate over each cell in the row
    for cell in row:
        if isinstance(cell, dict):
            # Extract the value associated with the 'alias' key
            value = cell.get('alias')
        else:
            value = None
        
        # Append the extracted value to the temporary list
        row_values.append(value)
    
    # Append the temporary list to the list of extracted values
    extracted_values.append(row_values)

# Create a new dataframe from the extracted values
categories_df3 = pd.DataFrame(extracted_values)

# Print the extracted values
#print(categories_df)

Put your parsed results into a DataFrame

In [146]:
#YELP_station1 = pd.merge(YELP_station1.drop('categories', axis=1), categories_df, left_index=True, right_index=True)
YELP_station1 = YELP_station1.rename(columns={0: 'Category 1', 1: 'Category 2', 2: 'Category 3'})
# Remove brackets from the location.display_address column
YELP_station1['location.display_address'] = YELP_station1['location.display_address'].apply(', '.join)
YELP_station1.head(2)

,id,alias,name,image_url,is_closed,url,review_count,categories,rating,transactions,...,coordinates.latitude,coordinates.longitude,location.address1,location.address2,location.address3,location.city,location.zip_code,location.country,location.state,location.display_address
0,11CNGukK207Mnz34FObMlA,planta-queen-coconut-grove-coconut-grove-7,PLANTA Queen Coconut Grove,https://s3-media1.fl.yelpcdn.com/bphoto/GcoCo0...,False,https://www.yelp.com/biz/planta-queen-coconut-...,349,"[{'alias': 'sushi', 'title': 'Sushi Bars'}, {'...",4.5,"[delivery, pickup]",...,25.728771,-80.242036,3015 Grand Ave,Ste 201,,Coconut Grove,33133,US,FL,"3, 0, 1, 5, , G, r, a, n, d, , A, v, e, ,, ..."
1,bqTmkGBOUV6ReXWk1BVa2w,kush-by-spillover-miami,Kush by Spillover,https://s3-media1.fl.yelpcdn.com/bphoto/Pp9mpa...,False,https://www.yelp.com/biz/kush-by-spillover-mia...,973,"[{'alias': 'breakfast_brunch', 'title': 'Break...",4.5,[delivery],...,25.728450,-80.240630,2911 Grand Ave,,Ste 400 D,Miami,33133,US,FL,"2, 9, 1, 1, , G, r, a, n, d, , A, v, e, ,, ..."

In [147]:
# Save the DataFrame to a pickle file
YELP_station1.to_pickle('YELP_station_Miami_Bikes_Station1.pk')

In [148]:
#YELP_station2 = pd.merge(YELP_station2.drop('categories', axis=1), categories_df2, left_index=True, right_index=True)
YELP_station2 = YELP_station2.rename(columns={0: 'Category 1', 1: 'Category 2', 2: 'Category 3'})
# Remove brackets from the location.display_address column
YELP_station2['location.display_address'] = YELP_station2['location.display_address'].apply(', '.join)
YELP_station2.head(2)

,id,alias,name,image_url,is_closed,url,review_count,categories,rating,transactions,...,coordinates.latitude,coordinates.longitude,location.address1,location.address2,location.address3,location.city,location.zip_code,location.country,location.state,location.display_address
0,d4pfwfJktfuTAQM51oj_ZQ,montys-coconut-grove-miami-5,Monty's Coconut Grove,https://s3-media1.fl.yelpcdn.com/bphoto/Ef17lm...,False,https://www.yelp.com/biz/montys-coconut-grove-...,1124,"[{'alias': 'seafood', 'title': 'Seafood'}, {'a...",3.0,"[delivery, pickup]",...,25.731964,-80.232184,2550 S Bayshore Dr,,,Miami,33133,US,FL,"2550 S Bayshore Dr, Miami, FL 33133"
1,WqIBKxRUPXH3NqTViAHLxQ,bayshore-club-bar-and-grill-miami,Bayshore Club Bar & Grill,https://s3-media1.fl.yelpcdn.com/bphoto/B7tTbJ...,False,https://www.yelp.com/biz/bayshore-club-bar-and...,464,"[{'alias': 'seafood', 'title': 'Seafood'}, {'a...",4.0,[],...,25.728996,-80.234543,3391 Pan American Dr,None,,Miami,33133,US,FL,"3391 Pan American Dr, Miami, FL 33133"

In [149]:
# Save the DataFrame to a pickle file
YELP_station2.to_pickle('YELP_station_Miami_Bikes_Station2.pk')

In [150]:
YELP_station3 = pd.merge(YELP_station3.drop('categories', axis=1), categories_df3, left_index=True, right_index=True)
YELP_station3 = YELP_station3.rename(columns={0: 'Category 1', 1: 'Category 2', 2: 'Category 3'})
# Remove brackets from the location.display_address column
YELP_station3['location.display_address'] = YELP_station3['location.display_address'].apply(', '.join)
YELP_station3.head(2)

,id,alias,name,image_url,is_closed,url,review_count,rating,transactions,price,...,location.address2,location.address3,location.city,location.zip_code,location.country,location.state,location.display_address,Category 1,Category 2,Category 3
0,WqIBKxRUPXH3NqTViAHLxQ,bayshore-club-bar-and-grill-miami,Bayshore Club Bar & Grill,https://s3-media1.fl.yelpcdn.com/bphoto/B7tTbJ...,False,https://www.yelp.com/biz/bayshore-club-bar-and...,464,4.0,[],$$,...,None,,Miami,33133,US,FL,"3391 Pan American Dr, Miami, FL 33133",seafood,tradamerican,wine_bars
1,bqTmkGBOUV6ReXWk1BVa2w,kush-by-spillover-miami,Kush by Spillover,https://s3-media1.fl.yelpcdn.com/bphoto/Pp9mpa...,False,https://www.yelp.com/biz/kush-by-spillover-mia...,973,4.5,[delivery],$$,...,,Ste 400 D,Miami,33133,US,FL,"2911 Grand Ave, Ste 400 D, Miami, FL 33133",breakfast_brunch,cocktailbars,newamerican

In [ ]:
# Save the DataFrame to a pickle file
YELP_station3.to_pickle('YELP_station_Miami_Bikes_Station3.pk')

# Comparing Results

Which API provided you with more complete data? Provide an explanation.

In [27]:
FSQ_Miami_Beach_POI.columns
#YELP_Miami_Beach_POI.columns

Index(['fsq_id', 'categories', 'geocodes', 'location', 'name', 'price',
       'rating', 'stats'],
      dtype='object')

In [116]:

YELP_Miami_Beach_POI.columns

Index(['id', 'alias', 'name', 'image_url', 'is_closed', 'url', 'review_count',
       'categories', 'rating', 'coordinates', 'transactions', 'price',
       'location', 'phone', 'display_phone', 'distance'],
      dtype='object')

Get the top 10 restaurants according to their rating

In [156]:
# Load the DataFrame from the Joining_data pickle file
df1 = pd.read_pickle('All_3_Miami_Stations_Combined.pk')
df1 = df1.sort_values(by = 'rating',ascending = False)
df1.head(10)

,City,CityLatLon,Company,Bike_Stations,latitude,longitude,free_bikes,empty_slots,id,name,review_count,rating,coordinates.latitude,coordinates.longitude,location.display_address,Category 1,Category 2,Category 3
46,"Miami Beach, Florida","25.790654,-80.1300455",DecoBike LLC,605 - Virginia St & Florida Ave,25.729275,-80.241581,16,0,VkBo1pXrYEBWIoaLf4wrkg,Morelia Ice Cream Paletas - Coconut Grove,44,5.0,25.727275,-80.242882,"3437 Main Hwy, Miami, FL 33133",icecream,desserts,kosher
96,"Miami Beach, Florida","25.790654,-80.1300455",DecoBike LLC,606 - S Bayshor Dr & Aviation Ave,25.732522,-80.233244,7,9,nVmMtacoiIKCYhKtxO9ZiA,Fookem's Fabulous Key Lime Pie,38,5.0,25.730116,-80.243001,"3081 Oak Ave, Coconut Grove, FL 33133",desserts,None,None
132,"Miami Beach, Florida","25.790654,-80.1300455",DecoBike LLC,608 - City Hall,25.728437,-80.234443,12,4,VkBo1pXrYEBWIoaLf4wrkg,Morelia Ice Cream Paletas - Coconut Grove,44,5.0,25.727275,-80.242882,"3437 Main Hwy, Miami, FL 33133",icecream,desserts,kosher
76,"Miami Beach, Florida","25.790654,-80.1300455",DecoBike LLC,606 - S Bayshor Dr & Aviation Ave,25.732522,-80.233244,7,9,VkBo1pXrYEBWIoaLf4wrkg,Morelia Ice Cream Paletas - Coconut Grove,44,5.0,25.727275,-80.242882,"3437 Main Hwy, Miami, FL 33133",icecream,desserts,kosher
90,"Miami Beach, Florida","25.790654,-80.1300455",DecoBike LLC,606 - S Bayshor Dr & Aviation Ave,25.732522,-80.233244,7,9,zjEdfLF4v8WqdkpDiPqjWg,Suite Habana Cafe,194,5.0,25.802000,-80.194780,"2609 N Miami Ave, Miami, FL 33127",coffee,bakeries,None
0,"Miami Beach, Florida","25.790654,-80.1300455",DecoBike LLC,605 - Virginia St & Florida Ave,25.729275,-80.241581,16,0,V3btCvWa1flTBYt2YKea_g,Bombay Darbar,1483,4.5,25.729350,-80.240789,"2901 Florida Ave, Miami, FL 33133",indpak,None,None
74,"Miami Beach, Florida","25.790654,-80.1300455",DecoBike LLC,606 - S Bayshor Dr & Aviation Ave,25.732522,-80.233244,7,9,WLXQNtdVm0sPbJ3MvCIyBw,B Bistro At The Grove,129,4.5,25.727521,-80.241149,"2895 McFarlane Rd, Miami, FL 33133",bakeries,breakfast_brunch,None
84,"Miami Beach, Florida","25.790654,-80.1300455",DecoBike LLC,606 - S Bayshor Dr & Aviation Ave,25.732522,-80.233244,7,9,M9QsnSNGdOzBqpGE0lcCaA,KruÌˆs Kitchen,42,4.5,25.727593,-80.242608,"3413 Main Hwy, Miami, FL 33133",salad,sandwiches,None
80,"Miami Beach, Florida","25.790654,-80.1300455",DecoBike LLC,606 - S Bayshor Dr & Aviation Ave,25.732522,-80.233244,7,9,FCdeRNd7KED4nPNcZeDEHA,Fireman Derekâ€™s Bake Shop,246,4.5,25.727250,-80.242740,"3435 Main Hwy, Miami, FL 33133",desserts,bakeries,coffee
78,"Miami Beach, Florida","25.790654,-80.1300455",DecoBike LLC,606 - S Bayshor Dr & Aviation Ave,25.732522,-80.233244,7,9,1kBe_QEv0I7MvG9sFyuCjw,Salt and Straw,149,4.5,25.728247,-80.241727,"3015 Grand Ave, Unit 145, Coconut Grove, FL 33133",icecream,desserts,None

In [124]:
YELP_Miami_Beach_POI.to_pickle('YELP_Miami_Beach_POI.pk2')

In [41]:
FSQ_Miami_Beach_POI2.to_pickle('FSQ_Miami_Beach_POI2.pk')